object Versions {
  lazy val akkaHttpVersion             = "10.2.6"
  lazy val akkaManagementVersion       = "1.1.1"
  lazy val akkaVersion                 = "2.6.17"
  lazy val awsSdkVersion               = "2.17.56"
  lazy val cassandraPersistenceVersion = "1.0.5"
  lazy val catsVersion                 = "2.6.1"
  lazy val jacksonVersion              = "2.11.4"
  lazy val jdbcPersistenceVersion      = "5.0.1"
  lazy val json4sVersion               = "4.0.3"
  lazy val kamonVersion                = "2.2.0"
  lazy val logbackVersion              = "1.2.9"
  lazy val mockitoVersion              = "3.9.0"
  lazy val mustacheVersion             = "0.9.0"
  lazy val openapi4jVersion            = "1.0.7"
  lazy val projectionVersion           = "1.2.1"
  lazy val s3Persistence               = "1.0.27"
  lazy val scalaMockVersion            = "5.1.0"
  lazy val scalaPactVersion            = "3.3.2-RC2"
  lazy val scalapbVersion              = "0.11.1"
  lazy val scalatestVersion            = "3.2.8"
  lazy val slickVersion                = "3.3.3"
}

object PDNDVersions {
  lazy val agreementManagementVersion         = "0.1.1-SNAPSHOT"
  lazy val attributeRegistryManagementVersion = "0.1.1-SNAPSHOT"
  lazy val catalogManagementVersion           = "0.1.1-SNAPSHOT"
  lazy val commonsVersion                     = "0.1.1-SNAPSHOT"
  lazy val partyManagementVersion             = "0.1.1-SNAPSHOT"
}
