object Versions {
  lazy val akkaHttpVersion        = "10.2.6"
  lazy val akkaManagementVersion  = "1.1.1"
  lazy val akkaVersion            = "2.6.17"
  lazy val awsSdkVersion          = "2.17.56"
  lazy val catsVersion            = "2.7.0"
  lazy val jacksonVersion         = "2.11.4"
  lazy val jdbcPersistenceVersion = "5.0.1"
  lazy val json4sVersion          = "4.0.4"
  lazy val kamonVersion           = "2.2.3"
  lazy val logbackVersion         = "1.2.9"
  lazy val mockitoVersion         = "3.9.0"
  lazy val mustacheVersion        = "0.9.0"
  lazy val openapi4jVersion       = "1.0.7"
  lazy val projectionVersion      = "1.2.1"
  lazy val s3Persistence          = "1.0.27"
  lazy val scalaMockVersion       = "5.2.0"
  lazy val scalaPactVersion       = "3.3.2"
  lazy val scalapbVersion         = "0.11.1"
  lazy val scalatestVersion       = "3.2.11"
  lazy val slickVersion           = "3.3.3"
}

object PagopaVersion {
  lazy val agreementManagementVersion         = "0.1.1"
  lazy val attributeRegistryManagementVersion = "0.1.1"
  lazy val authorizationManagementVersion     = "0.1.1"
  lazy val catalogManagementVersion           = "0.1.x-SNAPSHOT"
  lazy val commonsVersion                     = "0.1.1"
  lazy val partyManagementVersion             = "0.1.7"
}
