#!/bin/bash
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null
repository=$DOCKER_REPO

catalogManagementVersion="0.1"
agreementManagementVersion="0.1"
partyManagementVersion="0.1"
attributeRegistryManagementVersion="0.1"
authorizationManagementVersion="0.1"

wellKnownURL=$WELL_KNOWN_URL

mainAudience=$MAIN_AUDIENCE

catalogManagementUrl="http://interop-be-catalog-management.interop-be-catalog-management.svc.cluster.local:8088/catalog-management/"$catalogManagementVersion
agreementManagementUrl="http://interop-be-agreement-management.interop-be-agreement-management.svc.cluster.local:8088/agreement-management/"$agreementManagementVersion
partyManagementUrl="http://interop-be-party-management.interop-be-party-management.svc.cluster.local:8088/party-management/"$partyManagementVersion
attributeRegistryManagementUrl="http://interop-be-attribute-registry-management.interop-be-attribute-registry-management.svc.cluster.local:8088/attribute-registry-management/"$attributeRegistryManagementVersion
authorizationManagementUrl="http://interop-be-key-management.interop-be-key-management.svc.cluster.local:8088/key-management/"$keyManagementVersion

name=$(cat $SCRIPT_PATH/../build.sbt | grep "name :=" | awk -F:= '{ print $2 }' | sed 's/\"//' | sed 's/\",//' | sed 's/ //' | tr '[:upper:]' '[:lower:]' | grep -v client)

cd $SCRIPT_PATH/..
version=$(sbt -Dsbt.log.noformat=true 'inspect actual version' | grep "Setting: java.lang.String" | cut -d '=' -f2 | tr -d ' ')
cd $SCRIPT_PATH